<?php

$loggedUser = isset($_SESSION['user']) ? '<b>'.$_SESSION['user']['username'].'</b> :: <b>'.$_SESSION['user']['name'].'</b>' : 'an <b>Anonymous Person</b>';

$output = '<page_footer style="font-size: 7pt; color: #595959;">'
    .'<div class="hr" style="background: #595959;"></div>'
    .'This document is generated through <b>'.SYSTEM_NAME.' '.SYSTEM_VERSION.'</b>.<br />'
    .'Date of Generation: <b>'.date('Y-m-d @ H:i:s').'</b><br />'
    .'Generated by '.$loggedUser.'<br />'
    .'Lorma Colleges &copy; '.SYSTEM_YEAR_START.' - '.date('Y').'<br />'
    .'Page [[page_cu]] of [[page_nb]]'
    .'</page_footer>';

echo $output;
