<?php
$loggedUser = isset($_SESSION['user']) ? '<b>'.$_SESSION['user']['username'].'</b> :: <b>'.$_SESSION['user']['name'].'</b>' : 'an <b>Anonymous Person</b>';
?>

<page_footer style="font-size: 7pt; color: #595959;">
<div class="hr" style="background: #595959;"></div>
This document is generated through <b><?php echo SYSTEM_NAME,' ',SYSTEM_VERSION; ?></b><br />
Date of Generation: <b><?php echo date('Y-m-d @ H:i:s'); ?></b><br />
Generated by <?php echo $loggedUser; ?><br />
Lorma Colleges &copy; <?php echo SYSTEM_YEAR_START,' - ',date('Y'); ?><br />
Page [[page_cu]] of [[page_nb]]
</page_footer>
